# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trainingTab_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.trainingTab_2.setGeometry(QtCore.QRect(50, 20, 881, 641))
        self.trainingTab_2.setObjectName("trainingTab_2")
        self.trainingTab = QtWidgets.QWidget()
        self.trainingTab.setObjectName("trainingTab")
        self.trainImageLabel = QtWidgets.QLabel(self.trainingTab)
        self.trainImageLabel.setGeometry(QtCore.QRect(20, 20, 541, 561))
        self.trainImageLabel.setText("")
        self.trainImageLabel.setPixmap(QtGui.QPixmap("../../../.designer/backup/1.png"))
        self.trainImageLabel.setObjectName("trainImageLabel")
        self.groupBox = QtWidgets.QGroupBox(self.trainingTab)
        self.groupBox.setGeometry(QtCore.QRect(550, 50, 311, 501))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 211, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 211, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 211, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 211, 211))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.InputlineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.InputlineEdit.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.InputlineEdit.setObjectName("InputlineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(200, 20, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 291, 421))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.selectionAreaLabel = QtWidgets.QLabel(self.groupBox_2)
        self.selectionAreaLabel.setGeometry(QtCore.QRect(10, 40, 251, 201))
        self.selectionAreaLabel.setAutoFillBackground(True)
        self.selectionAreaLabel.setText("")
        self.selectionAreaLabel.setObjectName("selectionAreaLabel")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 181, 21))
        self.label_4.setObjectName("label_4")
        self.markerDelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.markerDelButton.setGeometry(QtCore.QRect(160, 380, 101, 41))
        self.markerDelButton.setObjectName("markerDelButton")
        self.markerAddButton = QtWidgets.QPushButton(self.groupBox_2)
        self.markerAddButton.setGeometry(QtCore.QRect(10, 380, 101, 41))
        self.markerAddButton.setObjectName("markerAddButton")
        self.markerTable = QtWidgets.QTableView(self.groupBox_2)
        self.markerTable.setGeometry(QtCore.QRect(10, 250, 251, 121))
        self.markerTable.setObjectName("markerTable")
        self.trainButton = QtWidgets.QPushButton(self.trainingTab)
        self.trainButton.setGeometry(QtCore.QRect(750, 570, 113, 40))
        self.trainButton.setObjectName("trainButton")
        self.algComboBox = QtWidgets.QComboBox(self.trainingTab)
        self.algComboBox.setGeometry(QtCore.QRect(660, 10, 191, 26))
        self.algComboBox.setObjectName("algComboBox")
        self.algLabel = QtWidgets.QLabel(self.trainingTab)
        self.algLabel.setGeometry(QtCore.QRect(550, 10, 91, 21))
        self.algLabel.setObjectName("algLabel")
        self.trainProgressBar = QtWidgets.QProgressBar(self.trainingTab)
        self.trainProgressBar.setGeometry(QtCore.QRect(550, 570, 111, 30))
        self.trainProgressBar.setProperty("value", 24)
        self.trainProgressBar.setObjectName("trainProgressBar")
        self.epochEdit = QtWidgets.QLineEdit(self.trainingTab)
        self.epochEdit.setGeometry(QtCore.QRect(680, 580, 61, 21))
        self.epochEdit.setObjectName("epochEdit")
        self.EPlabel = QtWidgets.QLabel(self.trainingTab)
        self.EPlabel.setGeometry(QtCore.QRect(680, 560, 60, 20))
        self.EPlabel.setObjectName("EPlabel")
        self.trainingTab_2.addTab(self.trainingTab, "")
        self.detectionTab = QtWidgets.QWidget()
        self.detectionTab.setObjectName("detectionTab")
        self.trainingTab_2.addTab(self.detectionTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.trainingTab_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ML Markers"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Marker Selection"))
        self.label_4.setText(_translate("MainWindow", "Selected Area"))
        self.markerDelButton.setText(_translate("MainWindow", "DELETE"))
        self.markerAddButton.setText(_translate("MainWindow", "ADD"))
        self.trainButton.setText(_translate("MainWindow", "Start Training"))
        self.algLabel.setText(_translate("MainWindow", "Algorithm"))
        self.EPlabel.setText(_translate("MainWindow", "Epochs"))
        self.trainingTab_2.setTabText(self.trainingTab_2.indexOf(self.trainingTab), _translate("MainWindow", "Training"))
        self.trainingTab_2.setTabText(self.trainingTab_2.indexOf(self.detectionTab), _translate("MainWindow", "Detection"))

import ml_rc
